import React from 'react';
import { motion } from 'motion/react';
import { useTranslation } from 'react-i18next';
import { ArrowLeft, Mail, Shield, FileText, Info, Feather } from 'lucide-react';

type LegalPageType = 'about' | 'privacy' | 'terms' | 'contact';

interface LegalPagesProps {
  type: LegalPageType;
  onBack: () => void;
}

export default function LegalPages({ type, onBack }: LegalPagesProps) {
  const { t } = useTranslation();

  const content = {
    about: {
      title: t('About Sato'),
      icon: <Info className="w-8 h-8" />,
      body: (
        <div className="space-y-8">
          <p className="text-xl leading-relaxed font-light text-[#7A7571]">
            {t('Sato was born from a simple observation: the crypto market never sleeps, but humans must. For KOLs and analysts, maintaining a 24/7 presence is a recipe for burnout.')}
          </p>
          <p className="text-lg leading-relaxed text-[#7A7571]">
            {t('Our mission is to bridge the gap between market speed and human capacity. By leveraging advanced AI models like Llama 3.3 and real-time market data, Sato creates content that isn\'t just automated—it\'s intelligent, contextual, and uniquely yours.')}
          </p>
          <div className="grid md:grid-cols-2 gap-12 pt-12 border-t border-[#EAE5DF]">
            <div>
              <h3 className="text-sm font-bold uppercase tracking-widest text-[#1A1918] mb-4">{t('Precision')}</h3>
              <p className="text-sm text-[#7A7571] leading-relaxed">{t('We don\'t just generate text. We generate real-time charts, perform multi-language translations, and maintain a consistent persona across every post.')}</p>
            </div>
            <div>
              <h3 className="text-sm font-bold uppercase tracking-widest text-[#1A1918] mb-4">{t('Security')}</h3>
              <p className="text-sm text-[#7A7571] leading-relaxed">{t('Your influence is your asset. We protect it with bank-grade encryption and a commitment to data privacy.')}</p>
            </div>
          </div>
        </div>
      )
    },
    privacy: {
      title: t('Privacy Policy'),
      icon: <Shield className="w-8 h-8" />,
      body: (
        <div className="space-y-8">
          <p className="text-xl leading-relaxed font-light text-[#7A7571]">
            {t('Your privacy is not a feature; it is a fundamental requirement. We handle your data with the same care we handle our own.')}
          </p>
          <div className="space-y-12">
            <section>
              <h3 className="text-sm font-bold uppercase tracking-widest text-[#1A1918] mb-6">{t('Data Encryption')}</h3>
              <p className="text-sm text-[#7A7571] leading-relaxed">{t('All API keys (Binance, Groq) are encrypted at the database level using Supabase Vault. We never see your raw keys, and they are only decrypted in a secure environment during post generation.')}</p>
            </section>
            <section>
              <h3 className="text-sm font-bold uppercase tracking-widest text-[#1A1918] mb-6">{t('Information Collection')}</h3>
              <p className="text-sm text-[#7A7571] leading-relaxed">{t('We collect only what is necessary: your email for account management and your configuration settings for the engine to function. We do not track your browsing habits or sell your data to third parties.')}</p>
            </section>
            <section>
              <h3 className="text-sm font-bold uppercase tracking-widest text-[#1A1918] mb-6">{t('Third-Party Services')}</h3>
              <p className="text-sm text-[#7A7571] leading-relaxed">{t('We use Supabase for infrastructure, Groq for AI inference, and Helio/MoonPay for payments. Each service has its own privacy standards that align with our commitment to security.')}</p>
            </section>
          </div>
        </div>
      )
    },
    terms: {
      title: t('Terms of Service'),
      icon: <FileText className="w-8 h-8" />,
      body: (
        <div className="space-y-8">
          <p className="text-xl leading-relaxed font-light text-[#7A7571]">
            {t('By using Sato, you agree to the following terms. Please read them carefully.')}
          </p>
          <div className="space-y-12">
            <section>
              <h3 className="text-sm font-bold uppercase tracking-widest text-[#1A1918] mb-6">{t('Not Financial Advice')}</h3>
              <p className="text-sm text-[#7A7571] leading-relaxed italic border-l-2 border-[#F3BA2F] pl-6">{t('Sato is a content generation tool. All output generated by the AI is for informational purposes only and does not constitute financial, investment, or trading advice. You are solely responsible for the content published to your accounts.')}</p>
            </section>
            <section>
              <h3 className="text-sm font-bold uppercase tracking-widest text-[#1A1918] mb-6">{t('Account Responsibility')}</h3>
              <p className="text-sm text-[#7A7571] leading-relaxed">{t('You are responsible for maintaining the security of your account and API keys. Sato Research Lab is not liable for any losses incurred due to unauthorized access or market volatility.')}</p>
            </section>
            <section>
              <h3 className="text-sm font-bold uppercase tracking-widest text-[#1A1918] mb-6">{t('Subscription & Refunds')}</h3>
              <p className="text-sm text-[#7A7571] leading-relaxed">{t('Subscriptions are billed in advance. Due to the nature of digital services and AI compute costs, all sales are final. You may cancel your subscription at any time to prevent future billing.')}</p>
            </section>
          </div>
        </div>
      )
    },
    contact: {
      title: t('Contact Support'),
      icon: <Mail className="w-8 h-8" />,
      body: (
        <div className="space-y-12">
          <p className="text-xl leading-relaxed font-light text-[#7A7571]">
            {t('Need assistance? Our team is here to help you optimize your automated presence.')}
          </p>
          <div className="bg-white border border-[#EAE5DF] rounded-sm p-12 shadow-sm inline-block">
            <h3 className="text-[10px] font-bold uppercase tracking-[0.4em] text-[#7A7571] mb-6">{t('Direct Email')}</h3>
            <a href="mailto:cypro123@outlook.com" className="text-2xl md:text-3xl font-serif font-medium text-[#1A1918] hover:text-[#7A7571] transition-colors underline decoration-[#EAE5DF] underline-offset-8">
              cypro123@outlook.com
            </a>
          </div>
          <div className="pt-12 border-t border-[#EAE5DF]">
            <p className="text-sm text-[#7A7571] leading-relaxed max-w-md">
              {t('For technical issues, please include your account email and a description of the problem. We typically respond within 24-48 hours.')}
            </p>
          </div>
        </div>
      )
    }
  };

  const activeContent = content[type];

  return (
    <motion.div 
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="min-h-screen bg-[#FBFBF9] selection:bg-[#EAE5DF]"
    >
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#FBFBF9]/80 backdrop-blur-md border-b border-[#EAE5DF]">
        <div className="max-w-screen-xl mx-auto px-6 lg:px-10 h-20 flex items-center justify-between">
          <button 
            onClick={onBack}
            className="flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.3em] text-[#7A7571] hover:text-[#1A1918] transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            {t('Back')}
          </button>
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-[#1A1918] rounded-sm flex items-center justify-center text-white">
              <Feather className="w-4 h-4" strokeWidth={3} />
            </div>
            <span className="font-serif text-xl tracking-tight font-medium">Sato</span>
          </div>
          <div className="w-20" /> {/* Spacer */}
        </div>
      </nav>

      {/* Content */}
      <main className="pt-40 pb-32 px-6 lg:px-10">
        <div className="max-w-screen-md mx-auto">
          <div className="flex items-center gap-6 mb-12">
            <div className="w-16 h-16 border border-[#EAE5DF] rounded-sm flex items-center justify-center text-[#1A1918] bg-white shadow-sm">
              {activeContent.icon}
            </div>
            <h1 className="text-5xl md:text-6xl font-serif font-medium text-[#1A1918] tracking-tight">
              {activeContent.title}
            </h1>
          </div>
          
          <div className="prose prose-neutral max-w-none">
            {activeContent.body}
          </div>
        </div>
      </main>

      {/* Footer-like closer */}
      <div className="max-w-screen-md mx-auto px-6 lg:px-10 pb-48">
        <div className="pt-16 border-t border-[#EAE5DF]">
          <span className="text-[9px] font-bold text-[#7A7571]/40 uppercase tracking-[0.5em]">© 2026 SATO RESEARCH LAB</span>
        </div>
      </div>
    </motion.div>
  );
}
